language: cpp

compiler:
  - gcc

env:
  global:
    # Coverity Scan token
    - secure: "b0ClZiz7IhJj265vifI7AiEdofPsiP4b7qNrHuLS+B3z0sHhhk5qCDrdR8Lcya531jxTxcyDlVK79s1fpnkSuMYeLXNO2QvJErwwBx26uVHUuRxx1zEaBRifsWpnR/UHCRFpP5YNC/xVi2EegSW+jCogrhBsOnzpiAXGUfbo3gllm3w4LCd8Lkw52WYQ+NkuSq0K0J5miOYLikxP3iVNzXcqhVjM/QUf71CEmzGUNMKKz/oXZ3PIP6HAz51b2v4JkNrpJ8krL6Bccmsfdvrfd2eQLt0rqUuuz1CtI1wboh/0i2n5Ef21N7zTpapwWl0W9q8QTJoJDzxvIAvAvF7e3bV9i++DUyUt+xfVTL8cBCelP5o5vQjsas9uQ6wfpLa3NTnuBhhliiDN4c3gdCgtmnwfP1nzsBOrGOLv6ZZG/DrkGdH4BssgT6g2OHTQMoA5oGyBbqJ6ZDWtqxCDuyEaqbn3CCZQnVirHmLfBGJ2nfZ2+J9RFP7a5rShgU3FC+FafCqWa4v+QgRWm/c99z2kl13D8BF4ulknHvZMrQd9AYk79leyGiO8fKf8WEBCPpEszg9lE40uUNLi0tUluZ248behpr1NSXgqaEOlrk+BCGKgwFFYGHqE9OaBk6Iv4e9NEUl/QItPncY+yWuceylDoPzBi2u06+oCpMbE7zgSsmk="
    - SMW_USE_SDL2=false

branches:
  only:
    - master
    - coverity_scan

sudo: false

before_install:
  - if [[ "$CXX" == "g++" ]]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - $CXX --version
  - cmake --version
  - cmake .

script:
  - make

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - gcc-4.8
    - g++-4.8
    - libsdl1.2-dev
    - libsdl-image1.2-dev
    - libsdl-mixer1.2-dev
  coverity_scan:
    project:
      name: "mmatyas/supermariowar"
      description: "Build submitted via Travis CI"
    notification_email: mmatyas@inf.u-szeged.hu
    build_command_prepend: "cmake ."
    build_command: "make"
    branch_pattern: coverity_scan
